name: Terraform CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  TF_VERSION: '1.5.0'
  AWS_REGION: 'us-west-2' # Update this with your preferred region

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Determine Terraform Directory
        id: tf_directory
        run: |
          # Check for changes in the dev directory
          if git diff --name-only HEAD^ HEAD | grep -q "envs/rev/dev/terraform.tfvars"; then
            echo "TF_DIR=envs/rev/dev" >> $GITHUB_ENV
          # Check for changes in the prod directory
          elif git diff --name-only HEAD^ HEAD | grep -q "envs/rev/prod/terraform.tfvars"; then
            echo "TF_DIR=envs/rev/prod" >> $GITHUB_ENV
          else
            echo "No relevant changes detected. Exiting."
            exit 0
          fi

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        env:
          TF_LOG: DEBUG
        run: terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -var-file=terraform.tfvars -auto-approve

      - name: Terraform destroy
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        working-directory: ${{ env.TF_DIR }}
        run: terraform destroy -var-file=terraform.tfvars -auto-approve