name: Terraform CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: "Deployment environment (dev or prod)"
        required: true
        type: choice
        options:
          - dev
          - prod

env:
  TF_VERSION: '1.5.0'
  AWS_REGION: 'us-west-2' # Update this with your preferred region

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

     - name: configure-aws-credential
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
        run: |
          echo "AWS credentials are set."

      - name: Determine Terraform Directory
        id: tf_directory
        run: |
          if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
            echo "TF_DIR=envs/rev/dev" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "prod" ]; then
            echo "TF_DIR=envs/rev/prod" >> $GITHUB_ENV
          else
            echo "Invalid environment specified"
            exit 1
          fi

      - name: Terraform Init
        working-directory: ${{ env.TF_DIR }}
        run: terraform init

      - name: Terraform Plan
        working-directory: ${{ env.TF_DIR }}
        run: terraform plan -var-file=terraform.tfvars

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -var-file=terraform.tfvars -auto-approve
